DROP DATABASE IF EXISTS employees;
CREATE DATABASE employees;

USE employees;

CREATE TABLE department(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
department_name VARCHAR(30),
PRIMARY KEY(id)
);

CREATE TABLE role(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INT UNSIGNED NOT NULL, 
PRIMARY KEY(id),
FOREIGN KEY(department_id) REFERENCES department(id)
);

CREATE TABLE employee(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT UNSIGNED NOT NULL,
manager_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY(role_id) REFERENCES role(id),
FOREIGN KEY(manager_id) REFERENCES employee(id)
);